package UAS;

import static UAS.dbkoneksi.koneksi;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Made Artha
 * TGL 24 Mei 2025
 */
public class formpenjualan extends javax.swing.JFrame {
      DefaultTableModel dtm = new DefaultTableModel();
    /**
     * Creates new form formBuku
     * @throws java.sql.SQLException
     */
    public formpenjualan() throws SQLException {
        initComponents();
        tblBuku.setModel(dtm);
        dtm.addColumn("idbarang");
        dtm.addColumn("namabarang");
        dtm.addColumn("hargabarang");
        dtm.addColumn("pembeli");
         
       
        
        lsDtbuku();
        fieldEnabled(false);
        tombol(false);
        cBARU.setEnabled(true);
        cTUTUP.setEnabled(true);
        
        
    }
    private void fieldEnabled(boolean opsi){
    txid.setEditable(opsi);
    txnama.setEditable(opsi);
    txharga.setEditable(opsi);
    txpembeli.setEditable(opsi);}
    
    private void tombol(boolean opsi){
    cBARU.setEnabled(opsi);
    cUBAH.setEnabled(opsi);
    cHAPUS.setEnabled(opsi);
    cTUTUP.setEnabled(opsi);
    }
     private void clearForm(){
         txid.setText("");
         txnama.setText("");
         txpembeli.setText("");
         txharga.setText("");
     }
    private void lsDtbuku() throws SQLException{
      Connection cnn = koneksi();
      dtm.getDataVector().removeAllElements();
      dtm.fireTableDataChanged();
      if( !cnn.isClosed() ){
          PreparedStatement ps = cnn.prepareStatement("SELECT * FROM jual;");
          ResultSet rs = ps.executeQuery();
          while( rs.next() ){
              Object[] dta = new Object[4];
              dta[0] = rs.getString("idbarang");
              dta[1] = rs.getString("namabarang");
               dta[2] = rs.getString("hargabarang");
              dta[3] = rs.getString("pembeli");
             
              
            dtm.addRow(dta);
          
          }
          cnn.close();
    }
    }
    private void storeData() throws SQLException{
        Connection cnn = koneksi();
        if(!cnn.isClosed()){
            PreparedStatement ps = cnn.prepareStatement("INSERT INTO jual(idbarang, namabarang, hargabarang, pembeli) VALUES(?,?,?,?);");
            ps.setString(1, txid.getText());
            ps.setString(2, txnama.getText());
            ps.setString(3, txharga.getText());
            ps.setString(4, txpembeli.getText());
            ps.executeUpdate();
            cnn.close();
        }
    }
    private void updateData() throws SQLException {
    Connection cnn = koneksi();
    if (!cnn.isClosed()) {
        PreparedStatement ps = cnn.prepareStatement(
            "UPDATE jual SET namabarang=?, hargabarang=?, pembeli=? WHERE idbarang=?;"
        );
        ps.setString(1, txnama.getText());
        ps.setInt(2, Integer.parseInt(txharga.getText()));
        ps.setString(3, txpembeli.getText());
        ps.setString(4, txid.getText());
        ps.executeUpdate();
        cnn.close();
    }


    }
    private void destoryData()throws SQLException{
        Connection cnn = koneksi();
        if(!cnn.isClosed()){
            PreparedStatement ps = cnn.prepareStatement("DELETE FROM jual WHERE idbarang=?;");
            ps.setString(1, txid.getText());
            ps.executeUpdate();
            cnn.close();
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txid = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txnama = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txharga = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txpembeli = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBuku = new javax.swing.JTable();
        cBARU = new javax.swing.JButton();
        cUBAH = new javax.swing.JButton();
        cHAPUS = new javax.swing.JButton();
        cTUTUP = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("daftar penjualan barang");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("idbarang");

        txid.setBackground(new java.awt.Color(204, 255, 255));
        txid.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txid.setForeground(new java.awt.Color(0, 204, 204));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("namabarang");

        txnama.setBackground(new java.awt.Color(204, 255, 255));
        txnama.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txnama.setForeground(new java.awt.Color(153, 255, 255));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("hargabarang");

        txharga.setBackground(new java.awt.Color(204, 255, 255));
        txharga.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("pembeli");

        txpembeli.setBackground(new java.awt.Color(204, 255, 255));
        txpembeli.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        tblBuku.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblBuku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBukuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblBuku);

        cBARU.setBackground(new java.awt.Color(0, 153, 204));
        cBARU.setText("Baru");
        cBARU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cBARUActionPerformed(evt);
            }
        });

        cUBAH.setBackground(new java.awt.Color(0, 153, 204));
        cUBAH.setText("Ubah");
        cUBAH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cUBAHActionPerformed(evt);
            }
        });

        cHAPUS.setBackground(new java.awt.Color(0, 153, 204));
        cHAPUS.setText("Hapus");
        cHAPUS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cHAPUSActionPerformed(evt);
            }
        });

        cTUTUP.setBackground(new java.awt.Color(0, 153, 204));
        cTUTUP.setText("Tutup");
        cTUTUP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cTUTUPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel2))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txid, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txharga, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txnama, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txpembeli, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 552, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(cBARU)
                        .addGap(18, 18, 18)
                        .addComponent(cUBAH)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cHAPUS)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cTUTUP))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(214, 214, 214)
                        .addComponent(jLabel1)))
                .addContainerGap(520, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txharga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(txpembeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cBARU, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cUBAH, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cHAPUS, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cTUTUP, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(123, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cHAPUSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cHAPUSActionPerformed
         if (!txid.getText().equals("")) {
        int konfirmasi = JOptionPane.showConfirmDialog(this, 
            "Yakin ingin menghapus data ini?", 
            "Konfirmasi Hapus", 
            JOptionPane.YES_NO_OPTION);

        if (konfirmasi == JOptionPane.YES_OPTION) {
            try {
                destoryData();          // Jalankan perintah hapus di database
                lsDtbuku();             // Refresh tabel
                clearForm();            // Kosongkan form input
                fieldEnabled(false);    // Nonaktifkan field input
                tombol(false);          // Nonaktifkan tombol aksi
                cBARU.setEnabled(true);
                cTUTUP.setEnabled(true);
                JOptionPane.showMessageDialog(this, "Data berhasil dihapus.");
            } catch (SQLException ex) {
                Logger.getLogger(formpenjualan.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(this, "Terjadi kesalahan saat menghapus data.");
            }
        }
    } else {
        JOptionPane.showMessageDialog(this, "Silakan pilih data yang ingin dihapus terlebih dahulu.");
    }
    }//GEN-LAST:event_cHAPUSActionPerformed

    private void cTUTUPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cTUTUPActionPerformed
       int opsi = JOptionPane.showOptionDialog(this, "Yakin akan Menup Form", "Konfirmasi Tutup Form", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE, null, null, null);
        if(opsi == JOptionPane.YES_OPTION)
        System.exit(0);
        
       
    }//GEN-LAST:event_cTUTUPActionPerformed

    private void tblBukuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBukuMouseClicked
       
    int row = tblBuku.getSelectedRow();

    txid.setText(tblBuku.getValueAt(row, 0).toString());
    txnama.setText(tblBuku.getValueAt(row, 1).toString());
    txharga.setText(tblBuku.getValueAt(row, 2).toString());
    txpembeli.setText(tblBuku.getValueAt(row, 3).toString());

    fieldEnabled(true);          // Aktifkan input supaya bisa edit
    tombol(false);               // Nonaktifkan tombol lain
    cUBAH.setEnabled(true);      // Hanya tombol ubah aktif
    cHAPUS.setEnabled(true);     // Dan tombol hapus


    }//GEN-LAST:event_tblBukuMouseClicked

    private void cBARUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cBARUActionPerformed
       if(cBARU.getText().equals("Baru")){
           cBARU.setText("Simpan");
           cTUTUP.setText("Batal");
           cUBAH.setEnabled(false);
           cHAPUS.setEnabled(false);
           clearForm();
           fieldEnabled(true);
       }else{
           if(!txid.getText().equals("")){
               try {
                   storeData();
                   lsDtbuku();
               } catch (SQLException ex) {
                   Logger.getLogger(formpenjualan.class.getName()).log(Level.SEVERE, null, ex);
               }
           }
           cBARU.setText("Baru");
           cTUTUP.setText("Tutup");
           clearForm();
           fieldEnabled(false);
           
       }
    }//GEN-LAST:event_cBARUActionPerformed

    private void cUBAHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cUBAHActionPerformed
                                         
                                       
    if (!txid.getText().equals("")) {
        try {
            updateData();            // Simpan ke database
            lsDtbuku();              // Refresh tabel
            clearForm();             // Kosongkan form
            fieldEnabled(false);     // Nonaktifkan input
            tombol(false);           // Nonaktifkan tombol kecuali Baru & Tutup
            cBARU.setEnabled(true);
            cTUTUP.setEnabled(true);
            JOptionPane.showMessageDialog(this, "Data berhasil diubah.");
        } catch (SQLException ex) {
            Logger.getLogger(formpenjualan.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan saat mengubah data.");
        }
    } else {
        JOptionPane.showMessageDialog(this, "Silakan pilih data dari tabel terlebih dahulu.");
    }

    }//GEN-LAST:event_cUBAHActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formpenjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formpenjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formpenjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formpenjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new formpenjualan().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(formpenjualan.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cBARU;
    private javax.swing.JButton cHAPUS;
    private javax.swing.JButton cTUTUP;
    private javax.swing.JButton cUBAH;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblBuku;
    private javax.swing.JTextField txharga;
    private javax.swing.JTextField txid;
    private javax.swing.JTextField txnama;
    private javax.swing.JTextField txpembeli;
    // End of variables declaration//GEN-END:variables

    private Object tblBukuSelectedRow(JTable tblBuku) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
